### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by NycuRO** [Bluplayz/Bedwars#5]
Hello ! Please You can create one video how configurate server for work plugin? Idk how ADD droping bricks ,iron ingots and gold ingots... And i'm test create one sign with : gold ,but not work. You can help me? I'm give you my server for help pls? :+1:

**Comment by erkam2002** [comment]
I can help you

**Comment by NycuRO** [comment]
Ok,you can speak me pls how add bricks ,iron ingots and gold ingots for pick out ?

**Comment by erkam2002** [comment]
Iron : Write on Sign EISEN under the iron block

**Comment by erkam2002** [comment]
Gold : Write under goldblock with sign GOLD

**Comment by erkam2002** [comment]
Brick : BRONZE

**Comment by NycuRO** [comment]
Thankssss :)

**Comment by NycuRO** [comment]
You can create Block Party MiniGame? :33

**Comment by Bluplayz** [comment]
i dont know what that is :D

**Comment by NycuRO** [comment]
Search on youtube : block party MiniGame :) ( Color Match )
