### ISSUE TITLE
Map load bug

### ISSUE THREAD

**Issue by AlicanCopurK** [Bluplayz/Bedwars#7]
Hi blu! Bug is 
[Server] [13:45:47] [Server thread/INFO]: [Bedwars] [Bedwars] Plugin wurde Erfolgreich Aktiviert!
[Server] [13:45:47] [Server thread/INFO]: [Bedwars] Arena BW2 wurde Erfolgreich geladen!
[Server] [13:45:47] [Server thread/CRITICAL]: pocketmine\utils\LevelException: "Invalid empty level name" (EXCEPTION) in "/src/pocketmine/Server" at line 1198

.

My softwate is genisys.

**Comment by Bluplayz** [comment]
i think you had setup the arena false
